; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = t4-i2s
boards_dir = boards

[env]
; Do not scan the project root as a library store, otherwise src is built twice.
;lib_extra_dirs = ${PROJECT_DIR}
lib_ignore = lib_deps
lib_ldf_mode = deep
platform = espressif32@6.3.0
framework = arduino
upload_speed = 1000000

;upload_speed = 115200
upload_protocol = esp-builtin

monitor_speed = 115200
;extra_scripts = pre:pre-build-script.py
board_build.partitions = partitions/ota_max_size_16MB.csv
build_type = debug                  ; ensures DWARF symbols in the ELF

;board_build.filesystem = littlefs

build_flags = 
	-D BOARD_HAS_PSRAM
	-D LV_CONF_INCLUDE_SIMPLE
	-D DISABLE_ALL_LIBRARY_WARNINGS
	-D DEFAULT_FTP_SERVER_NETWORK_TYPE_ESP32=NETWORK_ESP32
	-D DEFAULT_STORAGE_TYPE_ESP32=STORAGE_SD

; Enable UARDUINO_USB_CDC_ON_BOOT will start printing and wait for terminal access during startup
;	-D ARDUINO_USB_CDC_ON_BOOT=1

; Enable UARDUINO_USB_CDC_ON_BOOT will turn off printing and will not block when using the battery
    -D UARDUINO_USB_CDC_ON_BOOT
	-D CORE_DEBUG_LEVEL=5

monitor_filters =
	default
	esp32_exception_decoder

lib_deps = 
    https://github.com/scuba-hacker/LilyGo-AMOLED-Series
    https://github.com/scuba-hacker/TFT_eSPI#PushImageScaled
	https://github.com/scuba-hacker/AsyncElegantOTA
	esp32async/ESPAsyncWebServer
	esp32async/AsyncTCP
	https://github.com/xreef/SimpleFTPServer@3.0.2

[env:t4-i2s]
extends = env
board = T-Display-AMOLED

build_unflags = -std=gnu++11
    
build_flags = 
	${env.build_flags}
	-std=gnu++17
	-D LILYGO_TDISPLAY_AMOLED_SERIES
	
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

	-D USER_SETUP_LOADED=1 ; defined => User_Setup_Select.h is NOT loaded

	-D TFT_WIDTH=600
	-D TFT_HEIGHT=450

	;        -D ST7789_2_DRIVER=1
	;        -D TFT_RGB_ORDER=TFT_RGB

	-D TFT_INIT_DELAY=0x80


	-D TFT_NOP=0x00
	-D TFT_SWRST=0x01

	-D TFT_SLPIN=0x10
	-D TFT_SLPOUT=0x11

	-D TFT_INVOFF=0x20
	-D TFT_INVON=0x21

	-D TFT_DISPOFF=0x28
	-D TFT_DISPON=0x29

	-D TFT_CASET=0x2A
	-D TFT_PASET=0x2B
	-D TFT_RAMWR=0x2C

	-D TFT_RAMRD=0x2E

	-D TFT_MADCTL=0x36

	-D TFT_MAD_MY=0x80
	-D TFT_MAD_MX=0x40
	-D TFT_MAD_MV=0x20
	-D TFT_MAD_ML=0x10
	-D TFT_MAD_RGB=0x00
	-D TFT_MAD_BGR=0x08
	-D TFT_MAD_MH=0x04
	-D TFT_MAD_SS=0x02
	-D TFT_MAD_GS=0x01

	-D TFT_IDXRD=0x00
	
	
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D LOAD_FONT4=1
	-D LOAD_FONT6=1
	-D LOAD_FONT7=1
	-D LOAD_FONT8=1
	-D LOAD_GFXFF=1
	-D SMOOTH_FONT=1

    
